package com.sentinelops.audit.controller;

import java.util.List;

import org.springframework.http.ResponseEntity;
import org.springframework.security.access.prepost.PreAuthorize;
import org.springframework.web.bind.annotation.*;

import com.sentinelops.audit.entity.AuditLog;
import com.sentinelops.audit.service.AuditLogService;

import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.responses.ApiResponse;

@RestController
@RequestMapping("/api/audit")
@Tag(
        name = "Audit Logs",
        description = "APIs for viewing system audit logs"
)
public class AuditLogController {

    private final AuditLogService auditLogService;

    public AuditLogController(AuditLogService auditLogService) {
        this.auditLogService = auditLogService;
    }

    @Operation(
            summary = "Get All Audit Logs",
            description = """
                    Returns all audit logs generated by the system.

                    Each log contains:
                    • Action performed
                    • Username
                    • Incident reference
                    • Timestamp

                    Access: ADMIN only.
                    """
    )
    @ApiResponse(
            responseCode = "200",
            description = "Audit logs retrieved successfully"
    )
    @ApiResponse(
            responseCode = "401",
            description = "Unauthorized"
    )
    @ApiResponse(
            responseCode = "403",
            description = "Access denied"
    )
    @GetMapping
    @PreAuthorize("hasAuthority('ADMIN')")
    public ResponseEntity<List<AuditLog>> getAllLogs() {

        return ResponseEntity.ok(
                auditLogService.getAllLogs());
    }
}